###
GET https://
Content-Type: application/json

###
POST https://
Content-Type: application/json
{}

###
PUT https://
Content-Type: application/json
{}

###
DELETE https://
Content-Type: application/jsonContent-Type: application/json
